[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.145.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_BASEURL = "https://comment-gerer-son-budget.netlify.app/"

[[redirects]]
  from = "https://commentgerersonbudget.netlify.app/*"
  to = "https://comment-gerer-son-budget.netlify.app/:splat"
  status = 301
  force = true
